name: "Test"
on:
  pull_request:
  push:
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: nicknovitski/nix-develop@v1

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Run linter
      run: just lint
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Run tests
      run: just test
    - name: Run example tests
      run: just test_rust
    - name: Run example tests
      run: just cargo_version
