name: "Test"
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: nicknovitski/nix-develop@v1
    - name: Run tests
      run: just test
    - name: Run example tests
      run: just test_rust
    - name: Check cargo is installed
      run: just cargo_version
